apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ke5ebh414-go-gitops
  description: This is GitOps manifest for ke5ebh414-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ke5ebh414-go
    backstage.io/kubernetes-id: ke5ebh414-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ke5ebh414-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ke5ebh414-go
