apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ke5ebh414-go
  janus-idp.io/tekton: ke5ebh414-go
  backstage.io/kubernetes-id: ke5ebh414-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ke5ebh414-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
