apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ke5ebh414-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:68d95d10708fd1e0264111fbf8e79b93056a740b@sha256:1c4d04fd78753f52d0a331c97bec09639c5b1de4ce2ed6ac33974cb720851e0b
          name: container-image
